version: '3.1'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: football_db
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.50' # Limit to 50% of a CPU core
          memory: 512M # Limit to 512 MB

  mongoDb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M


  postgres-git:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: github
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '2.00' # Limit to 2 CPU cores
          memory: 4G # Limit to 4 GB
        reservations:
          cpus: '1.00' # Reserve 1 CPU core
          memory: 2G # Reserve 2 GB

  mongoDb-git:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: '2.00' # Limit to 2 CPU cores
          memory: 4G # Limit to 4 GB
        reservations:
          cpus: '1.00' # Reserve 1 CPU core
          memory: 2G # Reserve 2 GB