version: '3.1'
services:
  postgres:
    image: postgres
    mem_limit: 512m
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: football_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" , "-U", "postgres", "-d", "football_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
